language: generic

branches:
  only:
    - master

sudo: required

services:
  - docker

before_install:
  - docker pull base/archlinux

script:
  - docker run -t --rm=true base/archlinux /bin/sh -c "pacman -Syu --noconfirm make gcc git qt5-base qt5-declarative qt5-svg qt5-quickcontrols2 qt5-graphicaleffects qt5-multimedia aubio && git clone --recursive https://github.com/magnus-gross/quickpitch.git && cd quickpitch && mkdir build && cd build && qmake .. && make"

notifications:
  email:
    on_success: never
